ALTER TABLE V_PART ADD PRIMARY KEY (P_PARTKEY);
ALTER TABLE V_SUPPLIER ADD PRIMARY KEY (S_SUPPKEY);
ALTER TABLE V_PARTSUPP ADD PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY);
ALTER TABLE V_CUSTOMER ADD PRIMARY KEY (C_CUSTKEY);
ALTER TABLE V_ORDERS ADD PRIMARY KEY (O_ORDERKEY);
ALTER TABLE V_LINEITEM ADD PRIMARY KEY (L_ORDERKEY, L_LINENUMBER);
ALTER TABLE V_NATION ADD PRIMARY KEY (N_NATIONKEY);
ALTER TABLE V_REGION ADD PRIMARY KEY (R_REGIONKEY);